// Review data. To add a movie, copy one object in MOVIES and fill it in.
// rating is out of 5 (half stars allowed). color is the banner background behind the poster.
// Posters come from the TMDB image CDN (image.tmdb.org). TMDB's terms ask for attribution somewhere on the site.

var SITE = {
  updated: 'October 3, 2026',
  boxOfficeWeekend: 'Oct. 2-4'
};

var MOVIES = [
  {
    id: 'verity',
    title: 'Verity',
    status: '#1 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/Lr0Ng7Gg02RW1AyfYEL6P0WUvd.jpg',
    tmdbId: 1283515,
    director: 'Michael Showalter',
    cast: ['Dakota Johnson', 'Anne Hathaway', 'Josh Hartnett'],
    studio: 'Amazon MGM Studios',
    mpaa: 'R',
    runtime: '1h 55m',
    genres: ['Mystery', 'Thriller', 'Drama'],
    color: 'linear-gradient(135deg, #2a1a1a 0%, #5c2a2a 55%, #1a1a1a 100%)',
    rating: 2.5,
    headline: "A pulpy, tangled web of a thriller that's more about the game than the truth.",
    review: [
      "If you're looking for a high-brow psychological study, keep walking. But if you want a movie that feels like a glossy, high-stakes page-turner from a Colleen Hoover novel, Verity delivers exactly that. It's a guilty pleasure in the truest sense: vaguely illogical, highly dramatic, and completely absorbing.",
      "Dakota Johnson is great as Lowen, the struggling writer who finds herself in the middle of a domestic nightmare. She plays the uncertainty well, making you feel the creeping dread as she reads Verity's hidden autobiography. And then there's Anne Hathaway. Even when she's barely moving, she commands the screen, bringing a chilling presence to Verity that keeps you guessing about who the real monster is in the house.",
      "The movie leans hard into the 'erotic thriller' vibe of the 90s, which works for the most part. The tension between Lowen and Jeremy is palpable, and the twists come fast enough to keep you from questioning the plot holes too deeply. It's the kind of movie where you stop asking 'would this actually happen?' and just start asking 'what happens next?'",
      "Where it falters is in its third act. The resolution feels a bit rushed and simplifies some of the more interesting psychological threads the movie spent an hour building. It chooses a satisfying ending over a complex one, which might frustrate some, but for most, it'll be enough.",
      "It's not a masterpiece, and it's certainly not Gone Girl, but it's a blast of a ride. If you love pulpy mysteries and powerhouse performances, this is your kind of movie."
    ],
    bottomLine: "Vapid at times, but addictive throughout. A perfect 'guilty pleasure' watch.",
    scores: { rt: '34%', audience: '69%', metacritic: '45' },
    boxOffice: '$33M opening weekend',
    archived: false
  },
  {
    id: 'digger',
    title: 'Digger',
    status: '#2 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/1ATXKrIPJyKNwnJ6lcG088Sa6zi.jpg',
    tmdbId: 1248832,
    director: 'Alejandro G. Iñárritu',
    cast: ['Tom Cruise', 'John Goodman', 'Riz Ahmed', 'Sandra Hüller'],
    studio: 'Warner Bros.',
    mpaa: 'R',
    runtime: '2h 9m',
    genres: ['Satire', 'Comedy', 'Drama'],
    color: 'linear-gradient(135deg, #4a3a2a 0%, #8b6b4a 55%, #1a1a1a 100%)',
    rating: 3,
    headline: "Tom Cruise gives a career-best performance in a movie that's too loud for its own good.",
    review: [
      "I'll be honest: I went into Digger expecting a disaster movie. What I got was a movie about a disaster—both environmental and ego-driven. Alejandro G. Iñárritu has taken a massive swing here, attempting a Dr. Strangelove for the climate crisis, and while it doesn't always land, the effort is staggering.",
      "Tom Cruise is absolutely electric as Digger Rockwell. It's a performance of pure, unadulterated arrogance. He plays Digger not as a villain, but as a man who genuinely believes his own lies, and watching that delusion collide with a global catastrophe is the most entertaining part of the film. It's a transformative role that reminds you why Cruise is the biggest star in the world.",
      "The problem is that the movie is exhausting. It's loud, it's frantic, and the satire is often delivered with a sledgehammer rather than a scalpel. There are sequences that feel like they're trying too hard to be 'important,' and the meta-narrative with the play within the movie adds a layer of complexity that occasionally just feels like clutter.",
      "Still, the visual scale is immense. The imagery of the ice shelf collision is haunting and beautifully shot, providing a stark contrast to the frantic, claustrophobic energy of the political rooms. It's a movie that demands to be seen on a big screen, even if you spend half the time wanting to turn the volume down.",
      "Digger is a flawed, overstuffed, and frequently annoying movie, but it's also the most ambitious thing we've seen from Cruise in years. It's a bold misfire that's far more interesting than a safe success."
    ],
    bottomLine: "A chaotic, heavy-handed satire saved by a powerhouse lead performance.",
    scores: { rt: '52%', audience: '72%', metacritic: '45' },
    boxOffice: '$8.5M opening weekend',
    archived: false
  },
  {
    id: 'resident-evil',
    title: 'Resident Evil',
    status: '#3 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg',
    tmdbId: 1423191,
    director: 'Zach Cregger',
    cast: ['Austin Abrams', 'Zach Cherry', 'Kali Reis', 'Paul Walter Hauser', 'Sara Paxton'],
    studio: 'Columbia Pictures',
    mpaa: 'R',
    runtime: '1h 30m',
    genres: ['Horror', 'Action'],
    color: 'linear-gradient(135deg, #3a0d0d 0%, #8b1a1a 60%, #1a1a1a 100%)',
    rating: 4.5,
    headline: "Twenty-plus years of bad Resident Evil movies, and this is the one that finally gets it.",
    review: [
      "Let me be real with you. I did not expect to be writing a rave for a Resident Evil movie in 2026. This franchise has been rebooted so many times that the name alone used to make people groan. And yet here we are, with the best-reviewed movie in the whole series sitting at number one.",
      "Zach Cregger, the guy behind Barbarian, keeps it small and mean. Austin Abrams plays Bryan, a medical courier who just needs to drop a package at Raccoon City General, up in the snowy Colorado mountains. On the way in he hits someone with his car, and from there the night falls apart. There's an outbreak. There are things in the halls that used to be patients. And that package he's carrying turns out to be the one thing the doctors need to stop it. That's the whole movie: one guy, one hospital, one very bad night, done in about ninety minutes.",
      "What makes it work is that Cregger isn't trying to cram twenty years of game lore onto the screen. He's going after how those games feel. The dread before you open a door. Running low on ammo. Laughing because you're scared. Most of the monsters are practical effects, not CGI, and the creature work goes to some seriously gross places. You don't need to have played a single game to get it.",
      "Abrams plays a regular guy who is completely out of his depth. He talks to himself the whole way through, which is exactly what any of us would do, and it makes him easy to root for. Sara Paxton only shows up as a voice on the phone, and she still manages to rattle you.",
      "My one knock: the last stretch piles on so much action that it starts to wear you out, and if you want slow-burn scares, this leans more fun than frightening. But honestly? I'll take fun. After all these years, this series finally has a movie worth defending."
    ],
    bottomLine: "Fast, gross and a total blast. Grab some friends and see it loud.",
    scores: { rt: '96%', metacritic: '79', cinemascore: 'B+', audience: '91%' },
    boxOffice: '$120M total',
    archived: false
  },
  {
    id: 'primetime',
    title: 'Primetime',
    status: '#4 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    tmdbId: 1375441,
    director: 'Lance Oppenheim',
    cast: ['Robert Pattinson', 'Merritt Wever', 'Skyler Gisondo'],
    studio: 'A24',
    mpaa: 'R',
    runtime: '1h 50m',
    genres: ['Crime', 'Psychological Thriller', 'Drama'],
    color: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 55%, #0f3460 100%)',
    rating: 4,
    headline: "A skin-crawling look at the intersection of justice and entertainment.",
    review: [
      "Primetime is one of those movies that makes you feel like you need a shower after you leave the theater. It's a satirical dive into the production of 'To Catch a Predator,' and it doesn't hold back on how uncomfortable that entire cultural moment actually was.",
      "Robert Pattinson as Chris Hansen is a revelation. He captures that specific, predatory politeness—the soft-spoken tone and the slow, calculated delivery—that made the original show so terrifying for the people being caught. He doesn't play Hansen as a simple hero; he plays him as a man who has discovered a very lucrative way to weaponize public shame.",
      "The film is structured as a fever dream of 2006, with a visual style that mirrors the frantic, low-res energy of early reality TV. It brilliantly explores the ethics of the 'sting,' questioning where the line is between legitimate protection and a twisted form of entertainment. It's not always easy to watch, and at times it feels like it's trying too hard to be an 'important' critique.",
      "Merritt Wever and Skyler Gisondo provide great supporting turns, filling out the machinery of the production. They represent the banality of the process—the producers and decoys who treat these life-altering moments like just another day at the office.",
      "It's a disturbing, focused character study that manages to be both a critique of the media and a gripping thriller. It's not for everyone, but if you're in the mood for something that challenges your stomach and your ethics, this is it."
    ],
    bottomLine: "Intense, uncomfortable and brilliantly acted. A fascinating look at the dark side of reality TV.",
    scores: { rt: '96%', metacritic: '67' },
    boxOffice: '$30M total',
    archived: false
  },
  {
    id: 'forgotten-island',
    title: 'Forgotten Island',
    status: '#5 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/dGSsPovyUW5XVekXcy7F2GyhTEh.jpg',
    tmdbId: 1465063,
    director: 'Joel Crawford, Januel Mercado',
    cast: ['H.E.R.', 'Liza Soberano', 'Dave Franco', 'Lea Salonga'],
    studio: 'DreamWorks Animation',
    mpaa: 'PG',
    runtime: '1h 49m',
    genres: ['Animation', 'Fantasy', 'Adventure'],
    color: 'linear-gradient(135deg, #2e5a3e 0%, #7ba87b 55%, #d4e8d4 100%)',
    rating: 4,
    headline: "A candy-colored love letter to Filipino folklore and the bonds of friendship.",
    review: [
      "Every now and then, an animated movie comes along that feels truly fresh, and Forgotten Island is exactly that. It's a visually stunning, emotionally resonant journey that manages to be both a grand adventure and an intimate story about two best friends.",
      "The premise is simple but effective: Jo and Raissa are transported to Nakali, a world inspired by Filipino mythology, and they have to find a way home before they forget each other. The representation of Filipino culture here isn't just window dressing; it's woven into the very fabric of the world, from the creatures to the values of the characters. It's a beautiful, respectful, and imaginative execution.",
      "The voice cast is fantastic, with H.E.R. and Liza Soberano bringing a genuine chemistry to the lead roles. Dave Franco as a weredog is a highlight, providing much of the movie's comedic energy. The animation is vibrant and fluid, capturing the magical chaos of the island with a level of detail that's genuinely impressive.",
      "My only real complaint is the pacing. The middle section drags a bit as the characters move from one encounter to the next, and some of the emotional beats are played a little too heavily. It feels a bit too 'controlled' at times, as if the filmmakers were too worried about hitting every emotional mark perfectly.",
      "Despite that, the heart of the movie is undeniable. It's a story about the fear of growing apart and the effort it takes to hold onto the people who define you. It's a movie that will make you want to call your best friend the second the credits roll."
    ],
    bottomLine: "Imaginative, heartfelt and visually gorgeous. A must-watch for families and animation fans.",
    scores: { rt: '95%', audience: '96%', metacritic: '73' },
    boxOffice: '$20M total',
    archived: false
  },
  {
    id: 'heart-of-the-beast',
    title: 'Heart of the Beast',
    status: 'Opens Fri., Sept. 25',
    poster: 'https://image.tmdb.org/t/p/w500/1ApfSA8JTqeha3GTFEY8syV4auq.jpg',
    tmdbId: 1263337,
    director: 'David Ayer',
    cast: ['Brad Pitt', 'J.K. Simmons', 'Anna Lambe', 'Uber (as Odin)'],
    mpaa: 'PG-13',
    runtime: '1h 41m',
    genres: ['Drama', 'Adventure', 'Thriller'],
    color: 'linear-gradient(135deg, #1c2b33 0%, #3d5a66 55%, #c9d6dc 100%)',
    rating: 3.5,
    headline: "A man, his dog and a whole lot of Alaska. Your heart doesn't stand a chance.",
    review: [
      "I'll just say it up front: if there's a dog on the poster and that dog is in danger, I'm already in. Heart of the Beast knows exactly who it's for, and it doesn't pretend otherwise.",
      "Brad Pitt plays James Belmont, a retired Special Forces guy whose plane goes down in the middle of nowhere in Alaska. The only other survivor is Odin, the combat dog who served alongside him. They're both banged up, they're both still carrying the war with them, and the only way home is to walk. The movie keeps cutting back to their time overseas, and those scenes do a lot of heavy lifting. By the time you're back in the snow, you understand these two aren't owner and pet. They're partners.",
      "Here's the detail that sold me: Odin is played by Uber, a real search-and-rescue dog, not a pile of CGI. That matters. You can feel the difference when an animal is actually reacting to the person in front of it. Pitt goes quieter than usual, and early word is that the dog is the one people are talking about on the drive home.",
      "The wilderness looks gorgeous one minute and deadly the next, and David Ayer uses that well. Where it slips is the action. Belmont does things with a body that is clearly failing him that no human being could do, and you just have to shrug and go with it. The trek also drags in places. You could argue that's the point, since you're supposed to feel every mile, but a tighter cut would've helped.",
      "Early reviews are strong, and I get why. It's not a perfect movie. It's an honest one about loyalty, and that's enough to carry it."
    ],
    bottomLine: "A little far-fetched, a lot heartfelt. Dog people, this is your weekend.",
    scores: { rt: '89%' },
    boxOffice: 'Opens Sept. 25',
    archived: false
  },
  {
    id: 'practical-magic-2',
    title: 'Practical Magic 2',
    status: '#2 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/ogwQOLbCfncjvBhFb5l0OmQH8KC.jpg',
    tmdbId: 1302904,
    director: 'Susanne Bier',
    cast: ['Sandra Bullock', 'Nicole Kidman', 'Joey King', 'Lee Pace', 'Maisie Williams', 'Xolo Maridueña', 'Dianne Wiest', 'Stockard Channing'],
    studio: 'Warner Bros.',
    mpaa: 'PG-13',
    runtime: '2h 10m',
    genres: ['Fantasy', 'Romance', 'Comedy'],
    color: 'linear-gradient(135deg, #2e1a47 0%, #5b3a7a 55%, #1f3b2d 100%)',
    rating: 2.5,
    headline: "Bullock and Kidman still have the spark. Too bad the movie keeps getting in their way.",
    review: [
      "I wanted to love this one. A lot of us have a copy of the original that comes out every October like a family tradition, so getting Sandra Bullock and Nicole Kidman back as the Owens sisters, plus Dianne Wiest and Stockard Channing as the aunts, felt like a gift. The box office says plenty of you felt the same way.",
      "The curse is still there: any man who falls for an Owens woman is doomed. This time it lands on the next generation. Sally's daughter Kylie, played by Joey King, finds out the truth about the family when her boyfriend slips into a coma nobody can explain. To save him, the whole clan packs up and heads to England to dig into where the curse came from.",
      "And that's where it starts to drag. The plot feels like a checklist more than a story. Go here, find this clue, learn this secret, repeat. At over two hours, you feel every step of it. What made the first movie special was that it was a little wild and a little dangerous, and this one plays it safe from start to finish.",
      "The good news is that whenever Bullock and Kidman are on screen together, it comes alive. They still bicker and tease and protect each other like real sisters. Those scenes are the whole reason to go, and I wish the movie had trusted them more.",
      "Fans seem a lot happier with it than critics are, so if this franchise is your comfort food, you'll probably have a nice night. Just go in with your expectations in check."
    ],
    bottomLine: "For die-hard fans only. Everyone else, rewatch the original at home.",
    scores: { rt: '36%', metacritic: '44', cinemascore: 'B+', audience: '91%' },
    boxOffice: '$50.0M total after 2 weeks',
    archived: true
  },
  {
    id: 'spider-man-brand-new-day',
    title: 'Spider-Man: Brand New Day',
    status: '#3 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg',
    tmdbId: 969681,
    director: 'Destin Daniel Cretton',
    cast: ['Tom Holland', 'Zendaya', 'Sadie Sink', 'Jacob Batalon', 'Jon Bernthal', 'Florence Pugh', 'Mark Ruffalo', 'Marisa Tomei'],
    studio: 'Sony Pictures',
    mpaa: 'PG-13',
    runtime: '2h 25m',
    genres: ['Superhero', 'Action'],
    color: 'linear-gradient(135deg, #7a0f14 0%, #b3191f 45%, #0d1b3d 100%)',
    rating: 4,
    headline: "Nobody remembers Peter Parker. That's exactly what makes this one hit so hard.",
    review: [
      "Remember how the last one ended? The whole world forgot who Peter Parker was, including MJ and Ned. It was a gut punch, and I honestly wondered how they'd follow it. Brand New Day doesn't wave it away. It lives in it, and that's the smartest thing it does.",
      "It's been four years. Peter has gone all in on being Spider-Man, and New York is better for it, but his own life is a mess. Nobody knows him. Then his powers start changing in ways that are pretty unsettling, and he runs into a young telepathic mutant who is looking for her missing sister. It's heavier than the high school days, and it should be. This Peter has lost things.",
      "Tom Holland has been playing this guy for ten years now, and it shows in the best way. He's older, more tired and more alone, but he's still the kid who wants to do the right thing. Destin Daniel Cretton, who did Shang-Chi, gives the action a quick, bouncy energy that feels right for Spidey. And Jon Bernthal as the Punisher might be the best surprise here. He and Spider-Man play off each other so well, and he brings more heart to the part than you'd expect.",
      "It's not perfect. The first act crams in so many storylines and new characters that it gets crowded fast, and at two hours and twenty-five minutes it's long. Some threads are clearly being saved for the next movie. But it pulls itself together, and by the end it lands where it matters.",
      "Audiences love it and the box office speaks for itself. If you grew up with this character, bring a tissue. You might need it."
    ],
    bottomLine: "A grown-up, heartfelt Spider-Man that's a bit overstuffed but worth every minute.",
    scores: { rt: '90%', audience: '97%' },
    boxOffice: '$944.4M domestic after 8 weeks',
    archived: true
  },
  {
    id: 'the-odyssey',
    title: 'The Odyssey',
    status: '#4 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg',
    tmdbId: 1368337,
    director: 'Christopher Nolan',
    cast: ['Matt Damon', 'Tom Holland', 'Anne Hathaway', 'Robert Pattinson', "Lupita Nyong'o", 'Zendaya', 'Charlize Theron', 'Jon Bernthal', 'John Leguizamo'],
    studio: 'Universal Pictures',
    mpaa: 'R',
    runtime: '2h 52m',
    genres: ['Epic', 'Adventure', 'Drama'],
    color: 'linear-gradient(135deg, #0b2545 0%, #134074 50%, #8da9c4 100%)',
    rating: 4.5,
    headline: "Christopher Nolan takes on a 3,000-year-old story and makes it feel like it was written yesterday.",
    review: [
      "Ten weeks in, The Odyssey is still in the top five and has become the highest-grossing R-rated movie ever. That doesn't happen because of a marketing budget. It happens because people keep telling their friends to go.",
      "You probably know the story, even if it's been a while since school. The Trojan War is over, and Odysseus, the king of Ithaca, just wants to get home. It takes him ten years. Monsters, angry gods, islands you don't want to wash up on. Back home, his wife Penelope is holding off a houseful of men trying to take his place, and their son Telemachus is out searching for any sign his dad is still alive.",
      "Matt Damon plays Odysseus like a man who won the war and lost himself doing it. That's what gets me about this movie. It's huge and it's loud, but underneath it's about what winning actually costs, and about what people owe each other. That's a warmer, more human Nolan than we usually get, and it suits him.",
      "It also looks incredible. It was shot for 70mm, and the stop on Circe's island is the kind of sequence people walk out still arguing about how it was done. The cast is stacked. Robert Pattinson is a blast as one of the slimy suitors, John Leguizamo makes the most of a small role, and Zendaya gets a final scene that lands hard.",
      "Is it long? Yes. Nearly three hours, and your back will let you know. Nolan also takes some liberties with Homer that purists are grumbling about, and a few characters get less room than they deserve. Bring back the intermission, please. But this is the kind of movie theaters were made for."
    ],
    bottomLine: "A massive, moving epic. See it on the biggest screen you can find, and hit the restroom first.",
    scores: { rt: '94%', audience: '96%' },
    boxOffice: '$609.8M domestic after 10 weeks',
    archived: true
  },
  {
    id: 'coyote-vs-acme',
    title: 'Coyote vs. Acme',
    status: '#5 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg',
    tmdbId: 1204680,
    director: 'Dave Green',
    cast: ['Will Forte', 'Lana Condor', 'John Cena', 'Tone Bell', 'Martha Kelly', 'Luis Guzmán', 'Eric Bauza'],
    studio: 'Ketchup Entertainment',
    mpaa: 'PG',
    runtime: '1h 43m',
    genres: ['Comedy', 'Family', 'Animation'],
    color: 'linear-gradient(135deg, #c1440e 0%, #e89b3c 55%, #f5d27a 100%)',
    rating: 4.5,
    headline: "Wile E. Coyote finally gets his day in court, and it's one of the happiest surprises of the year.",
    review: [
      "This movie almost didn't make it. It was finished, shelved by the studio, written off as a tax loss, and only saved at the last minute by a small distributor. So the fact that it's now one of the best-reviewed movies of 2026? That's a real underdog story, and nobody deserves it more than the coyote.",
      "The idea is so good I can't believe nobody did it sooner. Cartoons and people live side by side, and Wile E. Coyote has had enough. Decades of rockets that blow up in his face, anvils that fall the wrong way, magnets that pull him off cliffs. So he hires a struggling personal injury lawyer, played by Will Forte, and sues the Acme Corporation. John Cena is on the other side. And of course the case digs up a lot more than a few bad warranties.",
      "It's funny, really funny, and not just for kids. The jokes come fast, the cartoon chaos is exactly what you want, and there's a sharp little jab at big corporations hiding just under the surface. It belongs right up there with the best movies that mix animation and live action.",
      "What caught me off guard is how much heart it has. Think about it: this is a character who has failed, badly and on camera, every single day of his life. Watching him finally stand up and ask whether it was really his fault is sweeter than it has any right to be.",
      "It's PG, it's under two hours, and audiences are loving it. Honestly, the grown-ups might have more fun than the kids."
    ],
    bottomLine: "Smart, silly and surprisingly sweet. Bring the whole family and root for the coyote.",
    scores: { rt: '96%', metacritic: '77', cinemascore: 'A', audience: '93%' },
    boxOffice: '$54.7M total after 4 weeks',
    archived: true
  },
  {
    id: 'the-weight',
    title: 'The Weight',
    status: '#9 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/8i5iZV50CoEtmDCFM7RSxCkpE8h.jpg',
    tmdbId: 1433583,
    director: 'Padraic McKinley',
    cast: ['Ethan Hawke', 'Russell Crowe', 'Julia Jones', 'Austin Amelio', 'Avi Nash', 'Lucas Lynggaard Tønnesen'],
    studio: 'Vertical Entertainment',
    mpaa: 'R',
    runtime: '1h 53m',
    genres: ['Thriller', 'Western', 'Drama'],
    color: 'linear-gradient(135deg, #3b2f22 0%, #6b5436 55%, #a88b5f 100%)',
    rating: 4,
    headline: "A tough, lean Depression-era thriller that deserves a lot more attention than it's getting.",
    review: [
      "This one opened quietly, ninth place and a little over two million dollars, and that's a shame, because it's one of the best thrillers in theaters right now. It's the kind of grown-up genre movie Hollywood hardly makes anymore, and I'm worried it'll be gone before people find it.",
      "It's 1933, the middle of the Depression, out in the Oregon woods. Ethan Hawke plays a World War I vet and widower who lands in prison after a fight in the street. All he cares about is getting back to his young daughter. So when he's offered a deal, early release if he hauls a load of gold bricks through rough country with a crew of other convicts, he takes it. You already know it isn't going to go smoothly.",
      "Hawke is the reason to go. He plays a man who is barely holding it together, and he never oversells it. Russell Crowe is here too, and putting those two on screen together is a treat. Old pros, no showboating, just good acting.",
      "The wild part is that this is Padraic McKinley's first movie as a director. There's no fat on it. Men, gold, bad weather and worse choices, and it just keeps tightening the screws. If I'm being picky, a few of the story beats are easy to see coming. But the tension is real, and the period details feel right.",
      "Catch it while you can. This is the sleeper of the season."
    ],
    bottomLine: "Gritty, gripping and anchored by Ethan Hawke. Don't let this one slip by.",
    scores: { rt: '93%', metacritic: '70', cinemascore: 'B+', audience: '83%' },
    boxOffice: '$2.3M opening weekend',
    archived: true
  },
  {
    id: 'hope',
    title: 'Hope',
    status: '#14 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/1n37BJchWHLiSYQkuFxe5KjB951.jpg',
    tmdbId: 1058424,
    director: 'Na Hong-jin',
    cast: ['Hwang Jung-min', 'Jo In-sung', 'Jung Ho-yeon', 'Taylor Russell', 'Cameron Britton'],
    mpaa: 'R',
    runtime: '2h 40m',
    genres: ['Sci-Fi', 'Horror', 'Action'],
    color: 'linear-gradient(135deg, #1a2e1a 0%, #3c5a2e 55%, #8b1a1a 100%)',
    rating: 3,
    headline: "A killer first hour, then a hard left turn that not everyone is going to follow.",
    review: [
      "Na Hong-jin made The Wailing, one of the scariest movies of the last decade, so Hope was near the top of my list this fall. And for the first hour or so, it's exactly what you'd hope for. Pun very much intended.",
      "A sleepy little town. A police force that is nowhere near ready for this. A string of brutal killings that might not be the work of anything human. Hwang Jung-min, Jo In-sung and Jung Ho-yeon lead the cast, and they're fantastic together. The first half moves like a freight train, scary, funny and wild all at once.",
      "Then it swerves, hard. Without spoiling anything, the movie becomes a full-on alien invasion story, and this is where it's going to split people. The switch feels more like the movie hitting the brakes than shifting into a higher gear. Some big ideas in the back half never get set up properly, and the effects are all over the map, from impressive to surprisingly cheap for a movie this ambitious.",
      "If you're good with a movie going completely off the rails, there's fun to be had. The monster action is big and loud, and going in knowing as little as possible definitely helps. But at two hours and forty minutes, that's a lot of time to ask for when the second half doesn't hold up.",
      "Reviews are mostly positive, and audiences seem split about the same way. I'd call it a wait-for-streaming for most people and a must-see for Na Hong-jin fans."
    ],
    bottomLine: "Worth it for the first hour and the cast. Just be ready for the second half to lose you.",
    scores: { rt: '78%', audience: '77%' },
    boxOffice: '$7.3M total after 2 weeks',
    archived: true
  },
  {
    id: 'the-end-of-oak-street',
    title: 'The End of Oak Street',
    status: '#19 at the box office',
    poster: 'https://image.tmdb.org/t/p/w500/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg',
    tmdbId: 1101383,
    director: 'David Robert Mitchell',
    cast: ['Anne Hathaway', 'Ewan McGregor', 'Christian Convery', 'Maisy Stella', 'Chris Coy'],
    mpaa: 'PG-13',
    runtime: '1h 39m',
    genres: ['Sci-Fi', 'Adventure'],
    color: 'linear-gradient(135deg, #2b3a1f 0%, #6b7f3a 55%, #d9a441 100%)',
    rating: 4,
    headline: "Dinosaurs in the cul-de-sac, 1982. It's the summer movie you'll want to watch again every year.",
    review: [
      "If you grew up on '80s Spielberg, the pitch alone should sell you. It's 1982, a regular family on a regular suburban street, and one night the present and the prehistoric world trade places. The next morning, there are dinosaurs in the neighborhood.",
      "This is from David Robert Mitchell, the guy who made It Follows, and he turns out to be really good at making a crowd-pleaser. Anne Hathaway and Ewan McGregor play the parents, and they give the whole thing a real sense of family. When it gets scary, and it does get scary, you care about these people, and that makes the tension so much better. It's been a while since a dinosaur movie actually made people nervous.",
      "The early '80s look is spot on. The houses, the clothes, the cars, the whole vibe feels like you pulled an old VHS tape off the shelf. The effects aren't flawless, but they have a scrappy charm that fits the era it's going for.",
      "It's not airtight. The movie never really explains why any of this is happening, and some of the side characters are pretty thin. The pace sags in a couple of spots. But it's a fun ride, and it's the kind of movie I can see people putting on every summer.",
      "It's been out six weeks and is on its way out of a lot of theaters, so if you want to see those dinosaurs on a big screen, go soon."
    ],
    bottomLine: "Pulpy, scary and full of '80s heart. Catch it before it leaves theaters.",
    scores: { rt: '86%', audience: '76%' },
    boxOffice: '$54.0M total after 6 weeks',
    archived: true
  }
];
